### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chaoscreater** [TheDen/slack-dm-purge#4]
Hi,

I've sent my token, installed the requirements via pip and getting this error:

Traceback (most recent call last):
  File "C:\Users\Blah\Desktop\slack-dm-purge-master\slack-dm-purge.py", line 57, in <module>
    slack_token = check_env_var_token(slack_token_env_var)
  File "C:\Users\Blah\Desktop\slack-dm-purge-master\slack-dm-purge.py", line 49, in check_env_var_token
    if slack_token_env_var in os.environ:
NameError: name 'os' is not defined

**Comment by TheDen** [comment]
Hey @chaoscreater (sorry for the lat reply), it should be fixed after this merge https://github.com/TheDen/slack-dm-purge/pull/5
